# SPDX-FileCopyrightText: 2025 EBFM Authors
#
# SPDX-License-Identifier: BSD-3-Clause

[tox]
min_version = 4.0
envlist = py{39,310,311,312,313}, type-check

[testenv]
deps = 
    pytest >= 7.0
    pytest-cov
extras = 
    dev

[testenv:unit]
description = Run unit tests
commands = 
    pytest tests/ -v --cov=src/ebfm --cov-report=term-missing
    
# [testenv:examples]
# description = Run examples
# commands = 
#   TODO

[testenv:py310levante] # Python version used on Levante
basepython = python3.10.10

[testenv:type-check]
description = Run static type checking
deps = 
    mypy
    types-setuptools
extras = 
    dev
commands = 
    mypy src/ebfm

[testenv:clean]
description = Clean up build and test artifacts
deps = 
skip_install = true
allowlist_externals = 
    rm
    find
commands = 
    rm -rf build/
    rm -rf dist/
    rm -rf .pytest_cache/
    rm -rf .coverage
    find . -type d -name "__pycache__" -delete
    find . -type f -name "*.pyc" -delete

[gh-actions]
python =
    3.9: py39
    3.10: py310 # Python Version used on Levante
    3.10: py310levante
    3.11: py311
    3.12: py312 # Development version used on Ubuntu 24.04
    3.13: py313 # Development version used on Ubuntu 25.04