# SPDX-FileCopyrightText: 2025 EBFM Authors
#
# SPDX-License-Identifier: BSD-3-Clause

name: Build and test
on:
  - push
  - pull_request

jobs:
  build-and-test:
    name: Build and test (${{ matrix.variant }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - variant: serial
            install_target: .
            run_mpi: false
          - variant: mpi
            install_target: .[mpi]
            run_mpi: true
    steps:
      - name: Checkout EBFM repository
        uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'
      - name: Setup MPI
        if: ${{ matrix.run_mpi }}
        uses: mpi4py/setup-mpi@v1
      - name: Create virtual environment and install EBFM
        run: |
          python3 -m venv .venv
          .venv/bin/python -m pip install --upgrade pip
          .venv/bin/pip install "${{ matrix.install_target }}"
      - name: Check Git version
        run: git --version
      - name: Check EBFM version
        run: .venv/bin/ebfm --version
      - name: Run example
        run: .venv/bin/ebfm --matlab-mesh examples/dem_and_mask.mat
      - name: Run example with restart
        run: |
          .venv/bin/ebfm --matlab-mesh examples/dem_and_mask.mat --restart-dir Reboot
          .venv/bin/ebfm --matlab-mesh examples/dem_and_mask.mat --restart-dir Reboot --restart-init --start-time "02-Jan-1979 00:00" --end-time "03-Jan-1979 00:00"
      - name: Run example with (pseudo) coupling
        run: .venv/bin/ebfm --matlab-mesh examples/dem_and_mask.mat --couple-to-icon --couple-to-elmer --fake-coupling --no-shading
      - name: Run example with MPI handshake
        if: ${{ matrix.run_mpi }}
        run: |
          # Run dummy script first; dummy on rank 0, EBFM on rank 1
          mpirun -np 1 .venv/bin/python tests/core/comm/mpi_handshake_dummy.py first : \
                 -np 1 .venv/bin/ebfm --matlab-mesh examples/dem_and_mask.mat --end-time "1-Jan-1979 03:00"
          # Run dummy script second; EBFM on rank 0, dummy on rank 1
          mpirun -np 1 .venv/bin/ebfm --matlab-mesh examples/dem_and_mask.mat --end-time "1-Jan-1979 03:00" : \
                 -np 1 .venv/bin/python tests/core/comm/mpi_handshake_dummy.py second

